<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - Abdallah Othman</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 0;
            padding: 0;
          }
          #header {
            background-color: #f8f9fa;
            padding: 20px;
            border-bottom: 1px solid #e9ecef;
          }
          #header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
          }
          #header p {
            margin: 5px 0 0;
            color: #666;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th {
            background-color: #f8f9fa;
            text-align: left;
            padding: 10px;
            border-bottom: 1px solid #e9ecef;
          }
          td {
            padding: 10px;
            border-bottom: 1px solid #e9ecef;
          }
          tr:hover {
            background-color: #f8f9fa;
          }
          .url {
            color: #0366d6;
            text-decoration: none;
          }
          .url:hover {
            text-decoration: underline;
          }
          .priority {
            color: #28a745;
          }
          .changefreq {
            color: #6c757d;
          }
          .lastmod {
            color: #6c757d;
          }
        </style>
      </head>
      <body>
        <div id="header">
          <h1>XML Sitemap</h1>
          <p>Generated by Astro Sitemap</p>
        </div>
        <table>
          <tr>
            <th>URL</th>
            <th>Priority</th>
            <th>Change Frequency</th>
            <th>Last Modified</th>
          </tr>
          <xsl:for-each select="sitemap:urlset/sitemap:url">
            <tr>
              <td>
                <a class="url">
                  <xsl:attribute name="href">
                    <xsl:value-of select="sitemap:loc"/>
                  </xsl:attribute>
                  <xsl:value-of select="sitemap:loc"/>
                </a>
              </td>
              <td class="priority">
                <xsl:value-of select="sitemap:priority"/>
              </td>
              <td class="changefreq">
                <xsl:value-of select="sitemap:changefreq"/>
              </td>
              <td class="lastmod">
                <xsl:value-of select="sitemap:lastmod"/>
              </td>
            </tr>
          </xsl:for-each>
        </table>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 